routes/web.php
<?php

Route::middleware('auth')->group(function () {
    Route::prefix('kiosk')->name('kiosk.')->group(function () {
        Route::get('/show', 'KioskController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\Kiosk');

        Route::get('/create', 'KioskController@create')
            ->name('create')
            ->middleware('can:create,App\Models\Kiosk');

        Route::get('/{kiosk}/edit', 'KioskController@edit')
            ->name('edit')
            ->middleware('can:edit,App\Models\Kiosk,kiosk');

        Route::get('{id}/delete', 'KioskController@destroy')
            ->name('delete')
            ->middleware('can:delete,App\Models\Kiosk');

        Route::post('/store', 'KioskController@store')
            ->name('store')
            ->middleware('can:create,App\Models\Kiosk');

        Route::post('/update', 'KioskController@update')
            ->name('update')
            ->middleware('can:update,App\Models\Kiosk');
    });

    Route::prefix('transaction')->name('transaction.')->group(function () {
        Route::get('/{kiosk_id}/show', 'TransactionController@getAllByKioskId')
            ->name('getAllByKioskId')
            ->middleware('can:view,App\Models\Transaction,kiosk_id');

        Route::get('/show', 'TransactionController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\Transaction');

        Route::post('/showFiltered', 'TransactionController@getAllFiltered')
            ->name('getAllFiltered')
            ->middleware('can:viewAny,App\Models\Transaction');
    });

    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/show', 'UserController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\User');

        Route::get('/create', 'UserController@create')
            ->name('create')
            ->middleware('can:create,App\Models\User');

        Route::get('/{id}/edit', 'UserController@edit')
            ->name('edit')
            ->middleware('can:update,App\Models\User');

        Route::get('{id}/delete', 'UserController@destroy')
            ->name('delete')
            ->middleware('can:delete,App\Models\User');

        Route::post('/store', 'UserController@store')
            ->name('store')
            ->middleware('can:create,App\Models\User');

        Route::patch('/update/{user}', 'UserController@update')
            ->name('update')
            ->middleware('can:update,App\Models\User');
    });
});

Auth::routes();

Route::auth(['register' => false]);
Route::get('/home', 'HomeController@index')
    ->name('home');

Route::get('/', function () {
    return redirect('home');
})->name('/');

app/Models/Kiosk.php
<?php

namespace App\Models;

use App\Enums\Role;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Kiosk extends Model
{
    protected $fillable = [
        'name', 'location', 'code', 'amount',
        'text_1', 'text_2', 'text_3', 'time_for_thanks',
        'text_speed', 'created_at', 'updated_at',
        'power_on_hour', 'power_off_hour', 'power_on_minute', 'power_off_minute'
    ];

    /**
     * Set the kiosk's power on hour column.
     *
     * @param  $value
     */
    public function setPowerOnHourAttribute($value)
    {
        $this->attributes['power_on_hour'] = date('H', strtotime($value));
    }

    /**
     * Set the kiosk's power on minute column.
     *
     * @param $value
     */
    public function setPowerOnMinuteAttribute($value) {
        $this->attributes['power_on_minute'] = date('i', strtotime($value));
    }

    /**
     * Set the kiosk's power off minute column.
     *
     * @param $value
     */
    public function setPowerOffMinuteAttribute($value) {
        $this->attributes['power_off_minute'] = date('i', strtotime($value));
    }

    /**
     * Set the kiosk's power off hour column.
     *
     * @param $value
     */
    public function setPowerOffHourAttribute($value) {
        $this->attributes['power_off_hour'] = date('H', strtotime($value));
    }

    /**
     * @param $value
     * @return int
     */
    public function getPowerOnHourAttribute($value) {
        if (strlen(strval($value)) === 1)
            return '0'.$value;
        else
            return $value;
    }

    /**
     * @param $value
     * @return int
     */
    public function getPowerOnMinuteAttribute($value) {
        if (strlen(strval($value)) === 1)
            return '0'.$value;
        else
            return $value;
    }

    /**
     * @param $value
     * @return int
     */
    public function getPowerOffMinuteAttribute($value) {
        if (strlen(strval($value)) === 1)
            return '0'.$value;
        else
            return $value;
    }

    /**
     * @param $value
     * @return int
     */
    public function getPowerOffHourAttribute($value) {
        if (strlen(strval($value)) === 1)
            return '0'.$value;
        else
            return $value;
    }

    /**
     * Get formatted created_at
     *
     * @param $value
     * @return
     */
    public function getCreatedAtAttribute($value) {
        return date('d.m.Y', strtotime($value));
    }

    /**
     * Get formatted battery_capacity
     *
     * @param $value
     * @return string
     */
    public function getBatteryCapacityAttribute($value) {
        return number_format($value, '3', '.', ' ');
    }

    /**
     * Get formatted current_battery_capacity
     *
     * @param $value
     * @return string
     */
    public function getCurrentBatteryCapacityAttribute($value) {
        return number_format($value, '3', '.', ' ');
    }

    /**
     * Get formatted current_battery_capacity
     *
     * @param $value
     * @return string
     */
    public function getBatteryVoltageAttribute($value) {
        return number_format($value, '3', '.', ' ');
    }

    /**
     * Insert kiosk to DB
     *
     * @param Request $request
     * @return bool
     */
    public function create(Request $request) {
        $kiosk = new Kiosk();
        $kiosk->fill($request->all());

        $kiosk->power_on_hour = $request->power_on_time;
        $kiosk->power_on_minute = $request->power_on_time;
        $kiosk->power_off_hour = $request->power_off_time;
        $kiosk->power_off_minute = $request->power_off_time;

        return $kiosk->save();
    }

    /**
     * update kiosk in DB
     *
     * @param Request $request
     * @return int
     */
    public function updateById(Request $request) {
        $kiosk = Kiosk::query()->findOrFail($request->id);
        $kiosk->fill($request->all());

        $kiosk->power_on_hour = $request->power_on_time;
        $kiosk->power_on_minute = $request->power_on_time;
        $kiosk->power_off_hour = $request->power_off_time;
        $kiosk->power_off_minute = $request->power_off_time;

        return $kiosk->save();
    }

    /**
     * Get all kiosks from DB
     *
     * @return array
     */
    public function getAll() {
        if (Auth::user()->role === Role::ADMIN) {
            return Kiosk::all();
        } else {
            $user = new User();
            $kiosksByUserId = $user->getKioskIdsByUserId(Auth::user()->id);
            $kiosks = [];
            foreach ($kiosksByUserId as $kiosk) {
                $result = Kiosk::where('kiosks.id', $kiosk->kiosk_id)
                                ->get();
                if ($result) {
                    array_push($kiosks, $result[0]);
                }
            }
            return $kiosks;
        }
    }

}

app/Http/Controllers/KioskController.php
<?php

namespace App\Http\Controllers;

use App\Enums\Role;
use App\Http\Requests\StoreKiosk;
use App\Http\Requests\UpdateKiosk;
use App\Models\Kiosk;
use App\Models\Transaction;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class KioskController extends Controller
{

    /**
     * return create page
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create() {
        return view('kiosk.create');
    }

    /**
     * Store kiosk in DB
     *
     * @param StoreKiosk $request
     * @param Kiosk $kiosk
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(StoreKiosk $request, Kiosk $kiosk) {
        $request->validated();

        if ($kiosk->create($request)) {
            flash('success')->success();
        }
        else {
            flash('error')->error();
        }

        return redirect()->route('kiosk.getAll');
    }

    /**
     * Edit kiosk by ID
     *
     * @param Kiosk $kiosk
     * @param Transaction $transaction
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Kiosk $kiosk, Transaction $transaction)
    {
        $transactions = $transaction->getAllByKioskIdLimited($kiosk->id);

        return view('kiosk.edit', [
            'kiosk' => $kiosk,
            'transactions' => $transactions
        ]);
    }

    /**
     * Destroy kiosk by ID
     *
     * @param int $id
     * @param Kiosk $kiosk
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(int $id, Kiosk $kiosk) {
        Kiosk::destroy($id);
        return redirect()->route('kiosk.getAll');
    }

    /**
     * Update kiosk
     *
     * @param UpdateKiosk $request
     * @param Kiosk $kiosk
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(UpdateKiosk $request, Kiosk $kiosk) {
        if (Auth::user()->role === Role::ADMIN) {
            $request->validated();
        }

        if ($kiosk->updateById($request)) {
            flash('success')->success();
        }
        else {
            flash('error')->error();
        }

        return redirect()->route('kiosk.getAll');
    }

    /**
     * Get all kiosks
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getAll(User $user) {
        $kioskAll = Kiosk::all();
        $kioskIds = $user->getKioskIdsByUserId(Auth::user()->id);

        if (Auth::user()->role === Role::ADMIN)
            return view('kiosk.table', [ 'table' => $kioskAll ]);
        else {
            $kiosksByUser = [];
            foreach ($kioskAll as $row) {
                foreach ($kioskIds as $kiosk) {
                    if (strval($row->id) === strval($kiosk->kiosk_id)) {
                        array_push($kiosksByUser, $row);
                    }
                }
            }

            return view('kiosk.table', ['table' => $kiosksByUser]);
        }
    }
}

resources/views/kiosk/create.blade.php
@extends('layouts.app_navbar_fixed')

@section('content')
    @include('layouts.sidebar')
    <div class="content-wrapper">
        <!-- Page header -->
        <div class="page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-add mr-2"></i> Přidat kiosek</h4>
                </div>

                <div class="header-elements d-none">
                    <div class="d-flex justify-content-center">
                        <a href="{{ route('kiosk.getAll') }}" class="btn btn-link btn-float text-purple-400">
                            <i class="icon-arrow-left52 text-purple-400"></i><span>Zpět</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
        <!-- /page header -->

        <!-- Content area -->
        <div class="content">
            {!! Form::open( ['route' => 'kiosk.store'] ) !!}

            <div class="card">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label for="name">Název kiosku</label>
                            <input type="text" class="form-control" id="name"
                                   aria-describedby="name" placeholder="Vložte název kiosku" name="name" required>
                        </div>
                        <div class="form-group col-sm">
                            <label for="location">Umístění kiosku</label>
                            <input type="text" class="form-control" id="location"
                                   placeholder="Vložte umístění kiosku" name="location" required>
                        </div>
                        <div class="form-group col-sm">
                            <label for="code">Kód kiosku</label>
                            <input type="text" class="form-control" id="code"
                                   placeholder="Vložte kód kiosku" name="code" required>
                        </div>
                    </div>
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label for="amount">Částka</label>
                            <input type="number" class="form-control" id="amount"
                                   aria-describedby="amount" placeholder="Vložte částku" name="amount" required>
                        </div>
                        <div class="form-group col-sm">
                            <label for="time_for_thanks">Délka zobrazení děkovací hlášky</label>
                            <input type="number" class="form-control" id="time_for_thanks"
                                   placeholder="30 sekund" name="time_for_thanks" required>
                        </div>
                    </div>
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label for="power_on_time">Nastavení času pro zapnutí</label>
                            <input type="time" class="form-control" id="power_on_time"
                                   aria-describedby="power_on_time" name="power_on_time" required>
                        </div>
                        <div class="form-group col-sm">
                            <label for="power_off_time">Nastavení času pro vypnutí</label>
                            <input type="time" class="form-control" id="power_off_time"
                                   aria-describedby="power_off_time" name="power_off_time" required>
                        </div>
                    </div>
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label for="text_1">Text 1</label>
                            <textarea class="form-control" rows="5" id="text_1" name="text_1"></textarea>
                        </div>

                        <div class="form-group col-sm">
                            <label for="text_2">Text 2</label>
                            <textarea class="form-control" rows="5" id="text_2" name="text_2"></textarea>
                        </div>

                        <div class="form-group col-sm">
                            <label for="text_3">Text 3</label>
                            <textarea class="form-control" rows="5" id="text_2" name="text_3"></textarea>
                        </div>
                    </div>
                    <div class="row justify-content-left">
                        <div class="form-group col-sm-6">
                            <label for="text_speed">Rychlost textu</label>
                            <input type="number" class="form-control" id="text_speed"
                                   aria-describedby="text_speed" placeholder="800 milisekund" name="text_speed" required>
                        </div>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-between">
                <button type="submit" class="btn bg-purple-400">
                    <i class="icon-floppy-disk mr-2"></i> Uložit
                </button>
                <a href="{{ URL::previous() }}" class="btn bg-grey-400">
                    Zpět
                </a>
            </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/kiosk/table.blade.php
@extends('layouts.app_navbar_fixed')

@section('content')
    @include('layouts.sidebar')
    <div class="content-wrapper">
        <!-- Page header -->
        <div class="page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-list-unordered mr-2"></i> Seznam kiosků</h4>
                </div>

                @if (Auth::user()->role == \App\Enums\Role::ADMIN)
                    <div class="header-elements d-none">
                        <div class="d-flex justify-content-center">
                            <a href="{{ route('kiosk.create') }}" class="btn btn-link btn-float text-purple-400"><i
                                    class="icon-add text-purple-400"></i><span>Přidat kiosek</span></a>
                        </div>
                    </div>
                @endif
            </div>
        </div>
        <!-- /page header -->

        <!-- Content area -->
        <div class="content">
            @include('flash::message')

            <div class="mb-3">
                <h6 class="mb-0 font-weight-semibold">
                    Celkový počet kiosků: {{ count($table) }}
                </h6>
            </div>

            <div class="row">
                @foreach($table as $kiosk)
                    <div class="col-sm-4">
                        <div class="card border-left-3 border-left-purple-400">
                            <div class="card-header header-elements-inline">
                                <h4 class="card-title">{{ $kiosk->name }}</h4>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="mb-2">
                                            <span class="font-weight-semibold"><i class="icon-price-tag2 mr-2"></i>Kód</span>
                                            <span class="font-size-base text-muted d-block">{{ $kiosk->code }}</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="mb-2">
                                            <span class="font-weight-semibold"><i class="icon-coins mr-2"></i>Částka</span>
                                            <span class="font-size-base text-muted d-block">{{ number_format($kiosk->amount, '0', ',', '.') }}</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="mb-2">
                                            <span class="font-weight-semibold"><i class="icon-battery-6 mr-2"></i>Baterie</span>
                                            <span class="font-size-base text-muted d-block">{{ number_format($kiosk->current_battery_capacity, '0', ',', ' ') }}/{{ number_format($kiosk->battery_capacity, '0', ',', ' ') }} mAh</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="mb-2">
                                    <span class="font-weight-semibold"><i class="icon-pin mr-2"></i>Umístění</span>
                                    <span class="font-size-base text-muted d-block">{{ $kiosk->location }}</span>
                                </div>

                            </div>
                            <div class="card-footer bg-white d-flex justify-content-between">
                                <ul class="list-inline mb-0">
                                    <li class="list-inline-item">
                                        <a href="{{ route('kiosk.edit', $kiosk->id) }}" class="btn-link text-purple-400">
                                            <i class="icon-pencil mr-2"></i>Nastavení kiosku
                                        </a>
                                    </li>
                                </ul>

                                <ul class="list-inline mb-0">
                                    <li class="list-inline-item">
                                        <a href="{{ route('transaction.getAllByKioskId', $kiosk->id) }}"
                                           class="btn-link text-purple-400">
                                            <i class="icon-calculator2 mr-2"></i>Seznam transakcí</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

            @if (Auth::user()->role == \App\Enums\Role::ADMIN)
                <a href="{{ route('kiosk.create') }}" class="btn bg-purple-400">
                    <i class="icon-add mr-2"></i> Přidat kiosek
                </a>
            @endif
        </div>
    </div>
@endsection