routes/web.php
<?php

Route::middleware('auth')->group(function () {
    Route::prefix('kiosk')->name('kiosk.')->group(function () {
        Route::get('/show', 'KioskController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\Kiosk');

        Route::get('/create', 'KioskController@create')
            ->name('create')
            ->middleware('can:create,App\Models\Kiosk');

        Route::get('/{kiosk}/edit', 'KioskController@edit')
            ->name('edit')
            ->middleware('can:edit,App\Models\Kiosk,kiosk');

        Route::get('{id}/delete', 'KioskController@destroy')
            ->name('delete')
            ->middleware('can:delete,App\Models\Kiosk');

        Route::post('/store', 'KioskController@store')
            ->name('store')
            ->middleware('can:create,App\Models\Kiosk');

        Route::post('/update', 'KioskController@update')
            ->name('update')
            ->middleware('can:update,App\Models\Kiosk');
    });

    Route::prefix('transaction')->name('transaction.')->group(function () {
        Route::get('/{kiosk_id}/show', 'TransactionController@getAllByKioskId')
            ->name('getAllByKioskId')
            ->middleware('can:view,App\Models\Transaction,kiosk_id');

        Route::get('/show', 'TransactionController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\Transaction');

        Route::post('/showFiltered', 'TransactionController@getAllFiltered')
            ->name('getAllFiltered')
            ->middleware('can:viewAny,App\Models\Transaction');
    });

    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/show', 'UserController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\User');

        Route::get('/create', 'UserController@create')
            ->name('create')
            ->middleware('can:create,App\Models\User');

        Route::get('/{id}/edit', 'UserController@edit')
            ->name('edit')
            ->middleware('can:update,App\Models\User');

        Route::get('{id}/delete', 'UserController@destroy')
            ->name('delete')
            ->middleware('can:delete,App\Models\User');

        Route::post('/store', 'UserController@store')
            ->name('store')
            ->middleware('can:create,App\Models\User');

        Route::patch('/update/{user}', 'UserController@update')
            ->name('update')
            ->middleware('can:update,App\Models\User');
    });
});

Auth::routes();

Route::auth(['register' => false]);
Route::get('/home', 'HomeController@index')
    ->name('home');

Route::get('/', function () {
    return redirect('home');
})->name('/');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Notifications\PasswordReset;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'surname', 'lastname',
        'customer', 'email_verified_at', 'role', 'active',
        'last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new PasswordReset($token));
    }

    /**
     * Get the kiosks.
     */
    public function kiosks()
    {
        return $this->belongsToMany(Kiosk::class, 'users_kiosk', 'user_id', 'kiosk_id');
    }

    /**
     * Update user by ID
     *
     * @param Request $request
     * @return int
     */
    public function updateById(Request $request) {
        $this->fill($request->except('password'));

        if ($password = $request->input('password')) {
            $this->setAttribute('password', Hash::make($password));
        }

        DB::beginTransaction();

        $this->kiosks()->sync($request->input('kiosks', []));
        $success = $this->save();

        DB::commit();

        return $success;
    }

    /**
     * Delete user by ID
     *
     * @param int $id
     */
    public function deleteById(int $id) {
        User::destroy($id);
    }

    /**
     * Insert user to DB
     *
     * @param Request $request
     * @return bool
     */
    public function create(Request $request) {
        $user = new User();

        $user->fill($request->all());
        $user->password = Hash::make($request->password);

        $isInserted = $user->save();

        if ($isInserted) {
            $response = User::where('name', $request->name)
                                ->where('email', $request->email)
                                ->get();
            if ($response)
                if ($request->kiosks)
                    foreach ($request->kiosks AS $selected_kiosk_id) {
                        $users_kiosk = new UsersKiosk();

                        $users_kiosk->user_id = $response[0]->id;
                        $users_kiosk->kiosk_id = $selected_kiosk_id;

                        $users_kiosk->save();
                    }
        }
        return $isInserted;
    }

    /**
     * Get kiosks by user ID
     *
     * @param int $id
     * @return array
     */
    public function getKioskIdsByUserId(int $id) {
        return UsersKiosk::where('user_id', $id)
                            ->get();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use App\Enums\Role;
use App\Http\Requests\StoreUser;
use App\Http\Requests\UpdateUser;
use App\Models\Kiosk;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{

    /**
     * Get all users
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getAll() {
        $table = User::all();

        foreach ($table as $row) {
            if ($row->role === Role::ADMIN) {
                $row->role = 'Administrátor';
            }
            else {
                $row->role = 'Zákazník';
            }
        }

        return view('user.table', [ 'table' => $table ]);
    }

    /**
     * Return view for create page
     *
     * @param Kiosk $kiosk
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Kiosk $kiosk) {
        $kiosks = $kiosk->getAll();
        return view('user.create', [
            'kiosks' => $kiosks,
        ]);
    }

    /**
     * Store user to DB
     *
     * @param StoreUser $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(StoreUser $request, User $user) {
        $request->validated();

        if ($user->create($request)) {
            flash('success')->success();
        }
        else {
            flash('error')->error();
        }

        return redirect()->route('user.getAll');
    }

    /**
     * Update user
     *
     * @param UpdateUser $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateUser $request, User $user) {
        $request->validated();

        if ($user->updateById($request)) {
            flash('success')->success();
        }
        else {
            flash('error')->error();
        }

        return redirect()->route('user.getAll');
    }

    /**
     * Return view for edit page
     *
     * @param $user_id
     * @param User $user
     * @param Kiosk $kiosk
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($userId, User $user , Kiosk $kiosk) {
        $userResult = User::query()->findOrFail($userId);

        if ($userResult->active) {
            $userResult->active = 'Aktivní';
        }
        else {
            $userResult->active = 'Neaktivní';
        }

        if ($userResult->role === Role::ADMIN) {
            $userResult->role = 'Administrátor';
        }
        else {
            $userResult->role = 'Zákazník';
        }

        if (!$userResult->last_login) {
            $userResult->last_login = 'Nikdy';
        }

        $kiosks = $kiosk->getAll();
        $kioskIds = $user->getKioskIdsByUserId($userId);
        $userKiosks = [];
        foreach ($kioskIds as $item) { // Convert from array of ObjClass to array of integer
            array_push($userKiosks, $item->kiosk_id);
        }

        return view('user.edit', [
            'user' => $userResult,
            'kiosks' => $kiosks,
            'user_kiosks' => $userKiosks,
        ]);
    }

    /**
     * Delete user from DB
     *
     * @param int $id
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $id, User $user) {
        $user->deleteById($id);
        return redirect()->route('user.getAll');
    }

}

resources/views/user/create.blade.php
@extends('layouts.app_navbar_fixed')

@section('content')
    @include('layouts.sidebar')
    <div class="content-wrapper">
        <!-- Page header -->
        <div class="page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-add mr-2"></i> Přidat uživatele</h4>
                </div>

                <div class="header-elements d-none">
                    <div class="d-flex justify-content-center">
                        <a href="{{ route('user.getAll') }}" class="btn btn-link btn-float text-purple-400">
                            <i class="icon-arrow-left52 text-purple-400"></i><span>Zpět</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page header -->

        <div class="content">
            {!! Form::open( ['route' => 'user.store'] ) !!}
            <div class="card">
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label for="name">Uživatelské jméno</label>
                            <input type="text" class="form-control" id="name"
                                   aria-describedby="name" placeholder="Vložte uživatelské jméno" name="name"
                                   required>
                        </div>

                        <div class="form-group col-sm">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email"
                                   aria-describedby="email" name="email" placeholder="Vložte email" required>
                        </div>
                    </div>
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label for="surname">Jméno</label>
                            <input type="text" class="form-control" id="surname"
                                   aria-describedby="surname" placeholder="Vložte jméno" name="surname"
                                   required>
                        </div>
                        <div class="form-group col-sm">
                            <label for="lastname">Příjmení</label>
                            <input type="text" class="form-control" id="lastname"
                                   placeholder="Vložte příjmení" name="lastname" required>
                        </div>
                    </div>
                    <div class="row justify-content-left">
                        <div class="form-group col-sm-6">
                            <label for="password">Heslo</label>
                            <input type="password" class="form-control" id="password"
                                   aria-describedby="password" placeholder="Vložte heslo" name="password"
                                   required>
                        </div>
                    </div>
                    {{--
                    <div class="form-group col-sm">
                        <label for="customer" hidden>Název subjektu</label>
                        <input type="text" class="form-control" id="customer"
                               aria-describedby="customer" name="customer"
                               placeholder="Vložte název subjektu">
                    </div>
                    --}}
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label for="role">Role</label>
                            <select class="form-control" id="role" name="role">
                                <option value="admin">Administrátor</option>
                                <option value="customer">Zákazník</option>
                            </select>
                        </div>
                        <div class="form-group col-sm">
                            <label for="active">Aktivní / Neaktivní</label>
                            <select class="form-control" id="active" name="active">
                                <option value=1>Aktivní</option>
                                <option value=0>Neaktivní</option>
                            </select>
                        </div>
                    </div>
                    <div class="row justify-content-left">
                        <div class="form-group col-sm">
                            <label>Přiřadit kiosek</label>
                            <div class="multiselect-native-select">
                                <select class="form-control multiselect-filtering" multiple="multiple"
                                        data-fouc="" name="kiosks[]">
                                    @foreach($kiosks as $kiosk)
                                        <option value="{{ $kiosk->id }}">#{{ $kiosk->code }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn bg-purple-400">
                    <i class="icon-floppy-disk mr-2"></i> Uložit
                </button>
                <a href="{{ URL::previous() }}" class="btn bg-grey-400">
                    Zpět
                </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app_navbar_fixed')

@section('content')
    @include('layouts.sidebar')
    <div class="content-wrapper">
        <!-- Page header -->
        <div class="page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-pencil mr-2"></i> Nastavení uživatele</h4>
                </div>

                <div class="header-elements d-none">
                    <div class="d-flex justify-content-center">
                        <a href="{{ route('user.getAll') }}" class="btn btn-link btn-float text-purple-400">
                            <i class="icon-arrow-left52 text-purple-400"></i><span>Zpět</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page header -->

        <div class="content">
            <div class="row">
                <div class="col-8">
                    {!! Form::open( ['url' => route('user.update', $user->id), 'method' => 'PATCH'] ) !!}
                    <div class="card">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="card-header">
                            <h5 class="card-title">Detail uživatele</h5>
                        </div>
                        <div class="card-body">
                            <div class="row justify-content-left">
                                <div class="form-group col-sm">
                                    <label for="name">Uživatelské jméno</label>
                                    <input type="text" class="form-control" id="name"
                                           aria-describedby="name" name="name"
                                           value="{{ $user->name }}" required>
                                </div>
                                <div class="form-group col-sm">
                                    <label for="email">Email</label>
                                    <input type="email" class="form-control" id="email"
                                           aria-describedby="email" name="email" value="{{ $user->email }}" required>
                                </div>

                            </div>
                            <div class="row justify-content-left">
                                <div class="form-group col-sm">
                                    <label for="surname">Jméno</label>
                                    <input type="text" class="form-control" id="surname"
                                           aria-describedby="surname" name="surname" value="{{ $user->surname }}" required>
                                </div>
                                <div class="form-group col-sm">
                                    <label for="lastname">Příjmení</label>
                                    <input type="text" class="form-control" id="lastname"
                                           name="lastname" value="{{ $user->lastname }}" required>
                                </div>
                            </div>
                            <div class="row justify-content-left">
                                <div class="form-group col-sm">
                                    <label for="password">Heslo</label>
                                    <input type="password" class="form-control" id="password"
                                           aria-describedby="password" name="password">
                                </div>
                                <div class="form-group col-sm">
                                    <label for="password_confirmation">Potvrdit heslo</label>
                                    <input type="password" class="form-control" id="password_confirmation"
                                           aria-describedby="password_confirmation" name="password_confirmation">
                                </div>
                            </div>
                            {{--
                            <div class="form-group col-sm">
                                <label for="customer">Název subjektu</label>
                                <input type="text" class="form-control" id="customer"
                                       aria-describedby="customer" name="customer" value="{{$user->customer}}"
                                       hidden>
                            </div>
                            --}}
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <div class="row justify-content-left">
                                <div class="form-group col-sm">
                                    <label for="role">Role</label>
                                    <select class="form-control" id="role" name="role">
                                        @if ($user->role === 'Administrátor')
                                            <option value="admin" selected>Administrátor</option>
                                            <option value="customer">Zákazník</option>
                                        @else
                                            <option value="admin">Administrátor</option>
                                            <option value="customer" selected>Zákazník</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group col-sm">
                                    <label for="active">Aktivní / Neaktivní</label>
                                    <select class="form-control" id="active" name="active">
                                        @if ($user->active === 'Aktivní')
                                            <option value=1 selected>Aktivní</option>
                                            <option value=0>Neaktivní</option>
                                        @else
                                            <option value=1>Aktivní</option>
                                            <option value=0 selected>Neaktivní</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="row justify-content-left">
                                <div class="form-group col-sm">
                                    <label>Přiřadit kiosek</label>
                                    <div class="multiselect-native-select">
                                        <select class="form-control multiselect-filtering" multiple="multiple"
                                                data-fouc="" name="kiosks[]">
                                            @foreach($kiosks as $kiosk)
                                                @if (in_array($kiosk->id, $user_kiosks))
                                                    <option value="{{ $kiosk->id }}" selected>#{{ $kiosk->code }}</option>
                                                @else
                                                    <option value="{{ $kiosk->id }}">#{{ $kiosk->code }}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-between">
                        <div>
                            <button type="submit" class="btn bg-purple-400">
                                <i class="icon-floppy-disk mr-2"></i> Uložit změny
                            </button>
                            <a href="{{ URL::previous() }}" class="btn bg-grey-400">
                                Zpět
                            </a>
                        </div>

                        <a href="{{ route('user.delete', $user->id) }}" class="delete">
                            <span id="del" class="btn btn-danger">Odstranit uživatele</span>
                        </a>
                    </div>

                    {!! Form::close() !!}
                </div>
                <div class="col-4">
                    <div class="content-wrapper">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Doplňující údaje</h5>
                            </div>

                            <div class="card-body">
                                <div class="row justify-content-left">
                                    <div class="form-group col-sm">
                                        <label for="created_at">Datum vytvoření</label>
                                        <input type="text" class="form-control" id="created_at"
                                               aria-describedby="created_at" name="created_at"
                                               value="{{ $user->created_at }}"
                                               disabled>
                                    </div>
                                    <div class="form-group col-sm">
                                        <label for="last_login">Poslední přihlášení</label>
                                        <input type="text" class="form-control" id="last_login"
                                               aria-describedby="last_login" name="last_login"
                                               value="{{ $user->last_login }}"
                                               disabled>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endsection

        @section('footer_scripts')
            <script>
                $(".delete").on("click", function () {
                    return confirm("Opravdu chcete smazat uživatele?");
                });
            </script>
@endsection

resources/views/user/table.blade.php
@extends('layouts.app_navbar_fixed')

@section('header_scripts')
    <script src="/js/global/js/datatables/user_datatables_basic.js"></script>
@endsection

@section('content')
    @include('layouts.sidebar')

    <div class="content-wrapper">
        <!-- Page header -->
        <div class="page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4><i class="icon-list-unordered mr-2"></i> Správa uživatelů</h4>
                </div>

                @if (Auth::user()->role == \App\Enums\Role::ADMIN)
                    <div class="header-elements d-none">
                        <div class="d-flex justify-content-center">
                            <a href="{{ route('user.create') }}" class="btn btn-link btn-float text-purple-400"><i
                                    class="icon-add text-purple-400"></i><span>Přidat uživatele</span></a>
                        </div>
                    </div>
                @endif
            </div>
        </div>
        <!-- /page header -->

        <!-- Content area -->
        <div class="content">
            <div class="card">
                <div class="card-body">
                    @include('flash::message')

                    <table class="table datatable-basic table-hover">
                        <thead>
                        <tr>
                            <th>Uživatelské jméno</th>
                            <th>Kontaktní osoba</th>
                            <th>E-mailová adresa</th>
                            <th>Role</th>
                            <th>Uživatelem od</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($table as $row)
                            <tr>
                                <td>{{ $row->name }}</td>
                                <td>{{ $row->surname }} {{ $row->lastname }}</td>
                                <td>{{ $row->email }}</td>
                                <td>{{ $row->role }}</td>
                                <td>{{ $row->created_at }}</td>
                                <td>{{ $row->active ? 'Aktivní' : 'Neaktivní' }}</td>
                                <td class="text-right">
                                    <a href="{{ route('user.edit', $row->id) }}"
                                       class="btn-link text-purple-400">
                                        <i class="icon-pencil mr-2"></i>Nastavení uživatele</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            @if (Auth::user()->role == \App\Enums\Role::ADMIN)
                <a href="{{ route('user.create') }}" class="btn bg-purple-400">
                    <i class="icon-add mr-2"></i> Přidat uživatele
                </a>
            @endif

        </div>
    </div>
@endsection