routes/web.php
<?php

Route::middleware('auth')->group(function () {
    Route::prefix('kiosk')->name('kiosk.')->group(function () {
        Route::get('/show', 'KioskController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\Kiosk');

        Route::get('/create', 'KioskController@create')
            ->name('create')
            ->middleware('can:create,App\Models\Kiosk');

        Route::get('/{kiosk}/edit', 'KioskController@edit')
            ->name('edit')
            ->middleware('can:edit,App\Models\Kiosk,kiosk');

        Route::get('{id}/delete', 'KioskController@destroy')
            ->name('delete')
            ->middleware('can:delete,App\Models\Kiosk');

        Route::post('/store', 'KioskController@store')
            ->name('store')
            ->middleware('can:create,App\Models\Kiosk');

        Route::post('/update', 'KioskController@update')
            ->name('update')
            ->middleware('can:update,App\Models\Kiosk');
    });

    Route::prefix('transaction')->name('transaction.')->group(function () {
        Route::get('/{kiosk_id}/show', 'TransactionController@getAllByKioskId')
            ->name('getAllByKioskId')
            ->middleware('can:view,App\Models\Transaction,kiosk_id');

        Route::get('/show', 'TransactionController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\Transaction');

        Route::post('/showFiltered', 'TransactionController@getAllFiltered')
            ->name('getAllFiltered')
            ->middleware('can:viewAny,App\Models\Transaction');
    });

    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/show', 'UserController@getAll')
            ->name('getAll')
            ->middleware('can:viewAny,App\Models\User');

        Route::get('/create', 'UserController@create')
            ->name('create')
            ->middleware('can:create,App\Models\User');

        Route::get('/{id}/edit', 'UserController@edit')
            ->name('edit')
            ->middleware('can:update,App\Models\User');

        Route::get('{id}/delete', 'UserController@destroy')
            ->name('delete')
            ->middleware('can:delete,App\Models\User');

        Route::post('/store', 'UserController@store')
            ->name('store')
            ->middleware('can:create,App\Models\User');

        Route::patch('/update/{user}', 'UserController@update')
            ->name('update')
            ->middleware('can:update,App\Models\User');
    });
});

Auth::routes();

Route::auth(['register' => false]);
Route::get('/home', 'HomeController@index')
    ->name('home');

Route::get('/', function () {
    return redirect('home');
})->name('/');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Charitativní kiosek / administrace') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="/css/global/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/layout.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/components.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/colors.min.css" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script src="/js/global/js/main/jquery.min.js"></script>
    <script src="/js/global/js/main/bootstrap.bundle.min.js"></script>
    <script src="/js/global/js/plugins/loaders/blockui.min.js"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script src="/js/assets/app.js"></script>
    <!-- /theme JS files -->
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</body>
</html>

resources/views/layouts/app_navbar_fixed.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Charitativní kiosek / administrace') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Favicons -->
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png"/>
    <link rel="icon" type="image/png" sizes="48x48" href="/images/favicon-48x48.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="57x57" href="/images/apple-touch-icon-57x57.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="60x60" href="/images/apple-touch-icon-60x60.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="72x72" href="/images/apple-touch-icon-72x72.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="76x76" href="/images/apple-touch-icon-76x76.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="114x114" href="/images/apple-touch-icon-114x114.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="120x120" href="/images/apple-touch-icon-120x120.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="144x144" href="/images/apple-touch-icon-144x144.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="152x152" href="/images/apple-touch-icon-152x152.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="180x180" href="/images/apple-touch-icon-180x180.png"/>
    <!-- /favicons -->

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="/css/global/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/layout.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/components.min.css" rel="stylesheet" type="text/css">
    <link href="/css/assets/colors.min.css" rel="stylesheet" type="text/css">
    <link href="/css/jquery.growl.css" rel="stylesheet" type="text/css" />
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script src="/js/global/js/main/jquery.min.js"></script>
    <script src="/js/global/js/main/bootstrap.bundle.min.js"></script>
    <script src="/js/global/js/plugins/loaders/blockui.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script src="/js/global/js/plugins/tables/datatables/datatables.min.js"></script>
    <script src="/js/global/js/plugins/forms/selects/select2.min.js"></script>

    <script src="/js/assets/app.js"></script>


    <script src="/js/global/js/plugins/forms/selects/bootstrap_multiselect.js"></script>
    <script src="/js/global/js/demo_pages/form_multiselect.js"></script>
    <!-- /theme JS files -->

    @yield ('header_scripts')

    <script src="/js/jquery.growl.js" type="text/javascript"></script>
    <link href="/css/jquery.growl.css" rel="stylesheet" type="text/css" />
</head>
<body class="navbar-top">
    <div class="navbar navbar-dark navbar-expand-md fixed-top">
        <div class="navbar-brand">
            <a href="/" class="d-inline-block">
                <img src="/images/logo_charitativni_kiosek-white.svg" alt="logo_charitativni_kiosek-white.svg">
            </a>
        </div>

        <div class="d-xl-none">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-demo3-mobile">
                <i class="icon-grid3"></i>
            </button>
        </div>

        <div class="navbar-collapse collapse" id="navbar-demo3-mobile">
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                @else
                    <li class="nav-item dropdown dropdown-user">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            <img src="/images/avatar-placeholder.jpg" class="rounded-circle mr-2" height="30" alt="">
                            <b>{{ Auth::user()->surname }} {{ Auth::user()->lastname }}</b>
                            <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
    <div class="page-content">
        @yield('content')
    </div>

    @yield ('footer_scripts')

</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        Navigation
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->


    <!-- Sidebar content -->
    <div class="sidebar-content">
        <!-- User menu -->
        <div class="sidebar-user">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3">
                        <a href="#"><img src="/images/avatar-placeholder.jpg" width="38" height="38"
                                         class="rounded-circle" alt=""></a>
                    </div>

                    <div class="media-body">
                        <div
                            class="media-title font-weight-semibold">{{ Auth::user()->surname }} {{ Auth::user()->lastname }}</div>
                        <div class="font-size-xs opacity-50">
                            @if (Auth::user()->role === \App\Enums\Role::ADMIN)
                                Administrátor
                            @else
                                Zákazník
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /user menu -->

        <!-- Main navigation -->
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                <li class="nav-item-header">
                    <div class="text-uppercase font-size-xs line-height-xs">Administrace</div>
                    <i class="icon-menu" title="Main"></i></li>

                <li class="nav-item">
                    <a href="{{route('transaction.getAll')}}" class="nav-link text-light">
                        <i class="icon-calculator2"></i>
                        <span>
									Seznam transakcí
								</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('kiosk.getAll')}}" class="nav-link text-light">
                        <i class="icon-list-unordered"></i>
                        <span>
									Seznam kiosků
								</span>
                    </a>
                </li>
                @if(Auth::user()->role === \App\Enums\Role::ADMIN)
                    <li class="nav-item">
                        <a href="{{route('user.getAll')}}" class="nav-link text-light">
                            <i class="icon-users"></i>
                            <span>
									Správa uživatelů
								</span>
                        </a>
                    </li>
                @endif

            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->

</div>